In [1]:
import pandas as pd
df_main = pd.read_excel("../sample_data_dictionary.xlsx", sheet_name=None)

In [2]:
# python -m ipykernel install --user --name main_venv --display-name "main_venv Kernel"

In [3]:
df_main.keys()

dict_keys(['data_dictionary', 'CUSTOMER', 'ACCOUNT', 'TRANSACTION', 'LOAN', 'BRANCH', 'DEPOSIT', 'PAYMENT'])

In [6]:
df_main['data_dictionary']

,Table Name,Column Name,Data Type,Description,Primary Key,Foreign Key,Example Data
0,CUSTOMER,customer_id,INT,Unique identifier for each customer,Yes,NaN,100012
1,CUSTOMER,first_name,VARCHAR(50),Customer’s first name,NaN,NaN,John
2,CUSTOMER,last_name,VARCHAR(50),Customer’s last name,NaN,NaN,Doe
3,CUSTOMER,date_of_birth,DATE,Date of birth of the customer,NaN,NaN,1989-05-24
4,CUSTOMER,gender,CHAR(1),Gender of the customer (M/F/O),NaN,NaN,M
5,CUSTOMER,email,VARCHAR(100),Contact email address,NaN,NaN,john.doe@email.com
6,CUSTOMER,join_date,DATE,Date customer joined the bank,NaN,NaN,2020-03-10
7,ACCOUNT,account_id,INT,Unique identifier for each account,Yes,NaN,200523
8,ACCOUNT,customer_id,INT,References the customer who owns this account,NaN,CUSTOMER.customer_id,100012
9,ACCOUNT,account_type,VARCHAR(20),"Type of account (e.g., Savings, Current)",NaN,NaN,Savings
10,ACCOUNT,open_date,DATE,Date account was opened,NaN,NaN,2020-03-11
11,ACCOUNT,balance,"DECIMAL(15,2)",Current account balance,NaN,NaN,2345.78
12,ACCOUNT,status,VARCHAR(10),Account status (Active/Closed/Frozen),NaN,NaN,Active
13,TRANSACTION,transaction_id,BIGINT,Unique identifier for each transaction,Yes,NaN,987654321
14,TRANSACTION,account_id,INT,References the account involved in the transac...,NaN,ACCOUNT.account_id,200523
15,TRANSACTION,transaction_date,DATETIME,Date and time of transaction,NaN,NaN,2024-05-22 13:24:55
16,TRANSACTION,transaction_type,VARCHAR(20),"Type (Deposit, Withdrawal, Transfer)",NaN,NaN,Withdrawal
17,TRANSACTION,amount,"DECIMAL(15,2)",Amount transacted,NaN,NaN,250
18,TRANSACTION,merchant,VARCHAR(100),Merchant or counterparty involved,NaN,NaN,Amazon
19,TRANSACTION,status,VARCHAR(10),Transaction status (Success/Failed/Pending),NaN,NaN,Success
20,LOAN,loan_id,INT,Unique identifier for each loan,Yes,NaN,300987
21,LOAN,customer_id,INT,References the customer who took the loan,NaN,CUSTOMER.customer_id,100012
22,LOAN,loan_amount,"DECIMAL(15,2)",Total loan amount,NaN,NaN,50000
23,LOAN,interest_rate,"DECIMAL(5,2)",Annual interest rate (%),NaN,NaN,7.5
24,LOAN,start_date,DATE,Loan start date,NaN,NaN,2021-01-15
25,LOAN,end_date,DATE,Expected loan end date,NaN,NaN,2026-01-15
26,LOAN,status,VARCHAR(15),Current loan status (Active/Closed/Defaulted),NaN,NaN,Active
27,BRANCH,branch_id,INT,Unique identifier for each branch,Yes,NaN,5001
28,BRANCH,branch_name,VARCHAR(100),Branch name,NaN,NaN,Central Branch
29,BRANCH,city,VARCHAR(50),City where the branch is located,NaN,NaN,Amsterdam
30,BRANCH,country,VARCHAR(50),Country of the branch,NaN,NaN,Netherlands
31,BRANCH,manager_id,INT,Employee ID of the branch manager,NaN,NaN,45002
32,DEPOSIT,deposit_id,INT,Unique identifier for each deposit,Yes,NaN,900001
33,DEPOSIT,account_id,INT,References the account where the deposit was made,NaN,ACCOUNT.account_id,200523
34,DEPOSIT,deposit_date,DATETIME,Date and time of deposit,NaN,NaN,2024-07-15 09:22:30
35,DEPOSIT,amount,"DECIMAL(15,2)",Amount deposited,NaN,NaN,1500
36,DEPOSIT,method,VARCHAR(30),"Deposit method (Cash, Cheque, Transfer)",NaN,NaN,Cash
37,DEPOSIT,branch_id,INT,Branch where the deposit occurred,NaN,BRANCH.branch_id,5001
38,DEPOSIT,status,VARCHAR(15),Deposit status (Completed/Pending/Failed),NaN,NaN,Completed
39,PAYMENT,payment_id,BIGINT,Unique identifier for each payment,Yes,NaN,800123456
40,PAYMENT,account_id,INT,Account from which the payment was made,NaN,ACCOUNT.account_id,200523
41,PAYMENT,recipient_name,VARCHAR(100),Name of the payment recipient,NaN,NaN,Electricity Company
42,PAYMENT,payment_date,DATETIME,Date and time of payment,NaN,NaN,2024-07-20 18:40:10
43,PAYMENT,amount,"DECIMAL(15,2)",Amount paid,NaN,NaN,75.25
44,PAYMENT,payment_type,VARCHAR(30),"Type of payment (Bill, Transfer, Loan, Tax)",NaN,NaN,Bill
45,PAYMENT,status,VARCHAR(15),Payment status (Success/Failed/Pending),NaN,NaN,Success

In [4]:
df_main['PAYMENT']

,Table Name,Column Name,Data Type,Description,Primary Key,Foreign Key,Example Data
0,PAYMENT,payment_id,BIGINT,Unique identifier for each payment,Yes,NaN,800123456
1,PAYMENT,account_id,INT,Account from which the payment was made,NaN,ACCOUNT.account_id,200523
2,PAYMENT,recipient_name,VARCHAR(100),Name of the payment recipient,NaN,NaN,Electricity Company
3,PAYMENT,payment_date,DATETIME,Date and time of payment,NaN,NaN,2024-07-20 18:40:10
4,PAYMENT,amount,"DECIMAL(15,2)",Amount paid,NaN,NaN,75.25
5,PAYMENT,payment_type,VARCHAR(30),"Type of payment (Bill, Transfer, Loan, Tax)",NaN,NaN,Bill
6,PAYMENT,status,VARCHAR(15),Payment status (Success/Failed/Pending),NaN,NaN,Success

In [5]:
df_main

{'data_dictionary':      Table Name       Column Name      Data Type  \
 0      CUSTOMER       customer_id            INT
 1      CUSTOMER        first_name    VARCHAR(50)
 2      CUSTOMER         last_name    VARCHAR(50)
 3      CUSTOMER     date_of_birth           DATE
 4      CUSTOMER            gender        CHAR(1)
 5      CUSTOMER             email   VARCHAR(100)
 6      CUSTOMER         join_date           DATE
 7       ACCOUNT        account_id            INT
 8       ACCOUNT       customer_id            INT
 9       ACCOUNT      account_type    VARCHAR(20)
 10      ACCOUNT         open_date           DATE
 11      ACCOUNT           balance  DECIMAL(15,2)
 12      ACCOUNT            status    VARCHAR(10)
 13  TRANSACTION    transaction_id         BIGINT
 14  TRANSACTION        account_id            INT
 15  TRANSACTION  transaction_date       DATETIME
 16  TRANSACTION  transaction_type    VARCHAR(20)
 17  TRANSACTION            amount  DECIMAL(15,2)
 18  TRANSACTION          merchant   VARCHAR(100)
 19  TRANSACTION            status    VARCHAR(10)
 20         LOAN           loan_id            INT
 21         LOAN       customer_id            INT
 22         LOAN       loan_amount  DECIMAL(15,2)
 23         LOAN     interest_rate   DECIMAL(5,2)
 24         LOAN        start_date           DATE
 25         LOAN          end_date           DATE
 26         LOAN            status    VARCHAR(15)
 27       BRANCH         branch_id            INT
 28       BRANCH       branch_name   VARCHAR(100)
 29       BRANCH              city    VARCHAR(50)
 30       BRANCH           country    VARCHAR(50)
 31       BRANCH        manager_id            INT
 32      DEPOSIT        deposit_id            INT
 33      DEPOSIT        account_id            INT
 34      DEPOSIT      deposit_date       DATETIME
 35      DEPOSIT            amount  DECIMAL(15,2)
 36      DEPOSIT            method    VARCHAR(30)
 37      DEPOSIT         branch_id            INT
 38      DEPOSIT            status    VARCHAR(15)
 39      PAYMENT        payment_id         BIGINT
 40      PAYMENT        account_id            INT
 41      PAYMENT    recipient_name   VARCHAR(100)
 42      PAYMENT      payment_date       DATETIME
 43      PAYMENT            amount  DECIMAL(15,2)
 44      PAYMENT      payment_type    VARCHAR(30)
 45      PAYMENT            status    VARCHAR(15)

                                           Description Primary Key  \
 0                 Unique identifier for each customer         Yes
 1                               Customer’s first name         NaN
 2                                Customer’s last name         NaN
 3                       Date of birth of the customer         NaN
 4                      Gender of the customer (M/F/O)         NaN
 5                               Contact email address         NaN
 6                       Date customer joined the bank         NaN
 7                  Unique identifier for each account         Yes
 8       References the customer who owns this account         NaN
 9            Type of account (e.g., Savings, Current)         NaN
 10                            Date account was opened         NaN
 11                            Current account balance         NaN
 12              Account status (Active/Closed/Frozen)         NaN
 13             Unique identifier for each transaction         Yes
 14  References the account involved in the transac...         NaN
 15                       Date and time of transaction         NaN
 16               Type (Deposit, Withdrawal, Transfer)         NaN
 17                                  Amount transacted         NaN
 18                  Merchant or counterparty involved         NaN
 19        Transaction status (Success/Failed/Pending)         NaN
 20                    Unique identifier for each loan         Yes
 21          References the customer who took the loan         NaN
 22                                  Total loan amount         NaN
 23                           Annual interest rate (%)         NaN
 24                                    Loan start date         NaN
 25                             Expected loan end date         NaN
 26      Current loan status (Active/Closed/Defaulted)         NaN
 27                  Unique identifier for each branch         Yes
 28                                        Branch name         NaN
 29                   City where the branch is located         NaN
 30                              Country of the branch         NaN
 31                  Employee ID of the branch manager         NaN
 32                 Unique identifier for each deposit         Yes
 33  References the account where the deposit was made         NaN
 34                           Date and time of deposit         NaN
 35                                   Amount deposited         NaN
 36            Deposit method (Cash, Cheque, Transfer)         NaN
 37                  Branch where the deposit occurred         NaN
 38          Deposit status (Completed/Pending/Failed)         NaN
 39                 Unique identifier for each payment         Yes
 40            Account from which the payment was made         NaN
 41                      Name of the payment recipient         NaN
 42                           Date and time of payment         NaN
 43                                        Amount paid         NaN
 44        Type of payment (Bill, Transfer, Loan, Tax)         NaN
 45            Payment status (Success/Failed/Pending)         NaN

              Foreign Key         Example Data
 0                    NaN               100012
 1                    NaN                 John
 2                    NaN                  Doe
 3                    NaN           1989-05-24
 4                    NaN                    M
 5                    NaN   john.doe@email.com
 6                    NaN           2020-03-10
 7                    NaN               200523
 8   CUSTOMER.customer_id               100012
 9                    NaN              Savings
 10                   NaN           2020-03-11
 11                   NaN              2345.78
 12                   NaN               Active
 13                   NaN            987654321
 14    ACCOUNT.account_id               200523
 15                   NaN  2024-05-22 13:24:55
 16                   NaN           Withdrawal
 17                   NaN                  250
 18                   NaN               Amazon
 19                   NaN              Success
 20                   NaN               300987
 21  CUSTOMER.customer_id               100012
 22                   NaN                50000
 23                   NaN                  7.5
 24                   NaN           2021-01-15
 25                   NaN           2026-01-15
 26                   NaN               Active
 27                   NaN                 5001
 28                   NaN       Central Branch
 29                   NaN            Amsterdam
 30                   NaN          Netherlands
 31                   NaN                45002
 32                   NaN               900001
 33    ACCOUNT.account_id               200523
 34                   NaN  2024-07-15 09:22:30
 35                   NaN                 1500
 36                   NaN                 Cash
 37      BRANCH.branch_id                 5001
 38                   NaN            Completed
 39                   NaN            800123456
 40    ACCOUNT.account_id               200523
 41                   NaN  Electricity Company
 42                   NaN  2024-07-20 18:40:10
 43                   NaN                75.25
 44                   NaN                 Bill
 45                   NaN              Success  ,
 'CUSTOMER':   Table Name    Column Name     Data Type  \
 0   CUSTOMER    customer_id           INT
 1   CUSTOMER     first_name   VARCHAR(50)
 2   CUSTOMER      last_name   VARCHAR(50)
 3   CUSTOMER  date_of_birth          DATE
 4   CUSTOMER         gender       CHAR(1)
 5   CUSTOMER          email  VARCHAR(100)
 6   CUSTOMER      join_date          DATE

                            Description Primary Key  Foreign Key  \
 0  Unique identifier for each customer         Yes          NaN
 1                Customer’s first name         NaN          NaN
 2                 Customer’s last name         NaN          NaN
 3        Date of birth of the customer         NaN          NaN
 4       Gender of the customer (M/F/O)         NaN          NaN
 5                Contact email address         NaN          NaN
 6        Date customer joined the bank         NaN          NaN

          Example Data
 0              100012
 1                John
 2                 Doe
 3          1989-05-24
 4                   M
 5  john.doe@email.com
 6          2020-03-10  ,
 'ACCOUNT':   Table Name   Column Name      Data Type  \
 0    ACCOUNT    account_id            INT
 1    ACCOUNT   customer_id            INT
 2    ACCOUNT  account_type    VARCHAR(20)
 3    ACCOUNT     open_date           DATE
 4    ACCOUNT       balance  DECIMAL(15,2)
 5    ACCOUNT        status    VARCHAR(10)

                                      Description Primary Key  \
 0             Unique identifier for each account         Yes
 1  References the customer who owns this account         NaN
 2       Type of account (e.g., Savings, Current)         NaN
 3                        Date account was opened         NaN
 4                        Current account balance         NaN
 5          Account status (Active/Closed/Frozen)         NaN

             Foreign Key Example Data
 0                   NaN       200523
 1  CUSTOMER.customer_id       100012
 2                   NaN      Savings
 3                   NaN   2020-03-11
 4                   NaN      2345.78
 5                   NaN       Active  ,
 'TRANSACTION':     Table Name       Column Name      Data Type  \
 0  TRANSACTION    transaction_id         BIGINT
 1  TRANSACTION        account_id            INT
 2  TRANSACTION  transaction_date       DATETIME
 3  TRANSACTION  transaction_type    VARCHAR(20)
 4  TRANSACTION            amount  DECIMAL(15,2)
 5  TRANSACTION          merchant   VARCHAR(100)
 6  TRANSACTION            status    VARCHAR(10)

                                          Description Primary Key  \
 0             Unique identifier for each transaction         Yes
 1  References the account involved in the transac...         NaN
 2                       Date and time of transaction         NaN
 3               Type (Deposit, Withdrawal, Transfer)         NaN
 4                                  Amount transacted         NaN
 5                  Merchant or counterparty involved         NaN
 6        Transaction status (Success/Failed/Pending)         NaN

           Foreign Key         Example Data
 0                 NaN            987654321
 1  ACCOUNT.account_id               200523
 2                 NaN  2024-05-22 13:24:55
 3                 NaN           Withdrawal
 4                 NaN                  250
 5                 NaN               Amazon
 6                 NaN              Success  ,
 'LOAN':   Table Name    Column Name      Data Type  \
 0       LOAN        loan_id            INT
 1       LOAN    customer_id            INT
 2       LOAN    loan_amount  DECIMAL(15,2)
 3       LOAN  interest_rate   DECIMAL(5,2)
 4       LOAN     start_date           DATE
 5       LOAN       end_date           DATE
 6       LOAN         status    VARCHAR(15)

                                      Description Primary Key  \
 0                Unique identifier for each loan         Yes
 1      References the customer who took the loan         NaN
 2                              Total loan amount         NaN
 3                       Annual interest rate (%)         NaN
 4                                Loan start date         NaN
 5                         Expected loan end date         NaN
 6  Current loan status (Active/Closed/Defaulted)         NaN

             Foreign Key Example Data
 0                   NaN       300987
 1  CUSTOMER.customer_id       100012
 2                   NaN        50000
 3                   NaN          7.5
 4                   NaN   2021-01-15
 5                   NaN   2026-01-15
 6                   NaN       Active  ,
 'BRANCH':   Table Name  Column Name     Data Type                        Description  \
 0     BRANCH    branch_id           INT  Unique identifier for each branch
 1     BRANCH  branch_name  VARCHAR(100)                        Branch name
 2     BRANCH         city   VARCHAR(50)   City where the branch is located
 3     BRANCH      country   VARCHAR(50)              Country of the branch
 4     BRANCH   manager_id           INT  Employee ID of the branch manager

   Primary Key  Foreign Key    Example Data
 0         Yes          NaN            5001
 1         NaN          NaN  Central Branch
 2         NaN          NaN       Amsterdam
 3         NaN          NaN     Netherlands
 4         NaN          NaN           45002  ,
 'DEPOSIT':   Table Name   Column Name      Data Type  \
 0    DEPOSIT    deposit_id            INT
 1    DEPOSIT    account_id            INT
 2    DEPOSIT  deposit_date       DATETIME
 3    DEPOSIT        amount  DECIMAL(15,2)
 4    DEPOSIT        method    VARCHAR(30)
 5    DEPOSIT     branch_id            INT
 6    DEPOSIT        status    VARCHAR(15)

                                          Description Primary Key  \
 0                 Unique identifier for each deposit         Yes
 1  References the account where the deposit was made         NaN
 2                           Date and time of deposit         NaN
 3                                   Amount deposited         NaN
 4            Deposit method (Cash, Cheque, Transfer)         NaN
 5                  Branch where the deposit occurred         NaN
 6          Deposit status (Completed/Pending/Failed)         NaN

           Foreign Key         Example Data
 0                 NaN               900001
 1  ACCOUNT.account_id               200523
 2                 NaN  2024-07-15 09:22:30
 3                 NaN                 1500
 4                 NaN                 Cash
 5    BRANCH.branch_id                 5001
 6                 NaN            Completed  ,
 'PAYMENT':   Table Name     Column Name      Data Type  \
 0    PAYMENT      payment_id         BIGINT
 1    PAYMENT      account_id            INT
 2    PAYMENT  recipient_name   VARCHAR(100)
 3    PAYMENT    payment_date       DATETIME
 4    PAYMENT          amount  DECIMAL(15,2)
 5    PAYMENT    payment_type    VARCHAR(30)
 6    PAYMENT          status    VARCHAR(15)

                                    Description Primary Key  \
 0           Unique identifier for each payment         Yes
 1      Account from which the payment was made         NaN
 2                Name of the payment recipient         NaN
 3                     Date and time of payment         NaN
 4                                  Amount paid         NaN
 5  Type of payment (Bill, Transfer, Loan, Tax)         NaN
 6      Payment status (Success/Failed/Pending)         NaN

           Foreign Key         Example Data
 0                 NaN            800123456
 1  ACCOUNT.account_id               200523
 2                 NaN  Electricity Company
 3                 NaN  2024-07-20 18:40:10
 4                 NaN                75.25
 5                 NaN                 Bill
 6                 NaN              Success  }